platform :ios, '9.0'

#source 'https://github.com/YLazyCat/AJAttributeLabel.git'

target 'AJAttributeLabel_Example' do
  pod 'AJAttributeLabel', :path => '../'

  target 'AJAttributeLabel_Tests' do
    inherit! :search_paths

  end
end
